# Generated by Django 4.2.2 on 2023-06-26 01:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lambda",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("body", models.TextField()),
                ("numberOfCalls", models.IntegerField(default=0)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
