# Generated by Django 4.2.2 on 2023-06-27 08:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("functions", "0002_lambda_owner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Lambda",
            new_name="Function",
        ),
    ]
