# Generated by Django 4.2.2 on 2023-08-05 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("functions", "0002_function_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="function",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="function",
            name="description",
            field=models.TextField(blank=True, default="-", null=True),
        ),
        migrations.AddField(
            model_name="function",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
