# Generated by Django 4.2.2 on 2023-08-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("functions", "0003_function_created_at_function_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="function",
            name="runtime",
            field=models.CharField(default="Python", max_length=20),
        ),
    ]
