# Generated by Django 4.2.2 on 2023-06-27 00:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_lst_of_functions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="lst_of_functions",
        ),
    ]
